version: 2
jobs:
  build:
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run: bash build.sh
      - persist_to_workspace:
          root: build
          paths:
            - paper.pdf
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: ./.circleci/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
