version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run: bash build.sh
      - persist_to_workspace:
          root: build
          paths:
            - paper.pdf
  deploy:
    working_directory: /tmp
    docker:
      - image: alpine/git
    steps:
      - attach_workspace:
          at: /tmp/build
      - run: ./.circleci/deploy.sh

workflows:
  version: 2
  btd:
    jobs:
      - build
      - deploy:
        requires:
          - build
